# Generated by Django 5.1.1 on 2025-01-14 06:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0022_category_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='description',
        ),
    ]
