# Generated by Django 5.1.1 on 2025-01-29 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0025_cartitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cartitem',
            options={'ordering': ['-date_added']},
        ),
    ]
