# Generated by Selenium IDE
import pytest
import time
import json
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.action_chains import ActionChains
from selenium.webdriver.support import expected_conditions
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.common.desired_capabilities import DesiredCapabilities

class TestApprove():
  def setup_method(self, method):
    self.driver = webdriver.Chrome()
    self.vars = {}
  
  def teardown_method(self, method):
    self.driver.quit()
  
  def test_approve(self):
    self.driver.get("http://127.0.0.1:8000/login/")
    self.driver.set_window_size(1366, 728)
    self.driver.find_element(By.ID, "email").click()
    self.driver.find_element(By.ID, "email").send_keys("nurturenest@gmail.com")
    self.driver.find_element(By.ID, "password").click()
    self.driver.find_element(By.ID, "password").send_keys("Admin@123")
    self.driver.find_element(By.ID, "password").send_keys(Keys.ENTER)
    self.driver.find_element(By.LINK_TEXT, "Total Registered Parents").click()
    self.driver.find_element(By.CSS_SELECTOR, ".activate").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) .status-button").click()
    self.driver.find_element(By.CSS_SELECTOR, ".activate").click()
    self.driver.find_element(By.CSS_SELECTOR, "tr:nth-child(5) .status-button").click()
    self.driver.find_element(By.LINK_TEXT, "NurtureNest").click()
    self.driver.find_element(By.LINK_TEXT, "Logout").click()
    self.driver.close()
  

# If running the script directly, use pytest to execute the test
if __name__ == "__main__":
    pytest.main([__file__])